default: &default
  adapter: postgresql
  encoding: utf8
  database: learn
  pool: 5
  host: localhost

development:
  <<: *default
  database: learn_dev

test:
  <<: *default
  database: learn_test

production:
  adapter: postgresql
  encoding: utf8
  database: learn_prod
  pool: 5
  username: <%= ENV["APP_DATABASE_USER"] %>
  password: <%= ENV["APP_DATABASE_PASS"] %>
